### ISSUE TITLE
写规则的一个问题

### ISSUE THREAD

**Issue by cognition9144** [jiacai2050/gooreplacer.xpi#10]
我想把
- https://**cdnjs.cloudflare.com/ajax/**libs/jquery/2.1.1/jquery.min.js

重定向到
- https://**cdnjscn.b0.upaiyun.com**/libs/jquery/2.1.1/jquery.min.js

试了以下规则，均无效：
1. cdnjs.cloudflare.com/ajax    ---->通配符--->  cdnjscn.b0.upaiyun.com  
2. http*://cdnjs.cloudflare.com/ajax   ---->通配符--->  https://cdnjscn.b0.upaiyun.com  
3. http*://cdnjs.cloudflare.com\/ajax\/(.*)$    ---->正则式--->  https://cdnjscn.b0.upaiyun.com/$1

不知道是哪里写错了呢？望解答。

**Comment by jiacai2050** [comment]
你写的那两个通配符 的重定向规则都是可以的呀，我这里测试了都能够正确跳转呀。

你是用的v0.8吗？

**Comment by cognition9144** [comment]
是的。难道是跟我的扩展冲突了…改天试试。
在 Jiacai Liu notifications@github.com，2015年2月19日 下午9:36写道：你写的那两个通配符 的重定向规则都是可以的呀，我这里测试了都能够正确跳转呀。

你是用的v0.8吗？
