### ISSUE TITLE
能提供 Firefox for Android 支持吗？

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jiacai2050/gooreplacer.xpi#11]
您开发的扩展非常好用，但是有一个小小的问题，就是我在 Firefox for Android 上面打开了 Mozilla ADD-ONS 地址（我有时喜欢用这个浏览器在手机上打开 [Web QR](http://webqr.com/) 扫二维码，这个网站也用了谷歌的接口），按下“添加到 Firefox”以后得到的却是“无法安装”的提示，不知您能否解决下这个问题？

**Comment by jiacai2050** [comment]
有些API不支持android平台，我可以把那些API去掉，但是这样就不能自定义了，只能把重定向规则硬编码在代码中。

**Comment by KrasnayaPloshchad** [comment]
哦～那就试试看还有木有别的法子解决在 Fennec 上面自定义的问题，如果实在不行就可以考虑开一个分支版本。

**Comment by ivysrono** [comment]
@jiacai2050 其实不能自定义在android上不是什么大问题……

**Comment by jiacai2050** [comment]
@renyouguo 
已经在开发中了
https://github.com/jiacai2050/gooreplacer/tree/android

**Comment by KrasnayaPloshchad** [comment]
应该在 AMO 上架，因为火狐安卓版只认 AMO 安装的扩展。

**Comment by jiacai2050** [comment]
@KrasnayaPloshchad @renyouguo 
目前可以按照 [README中的说明](https://github.com/jiacai2050/gooreplacer/tree/android#安装)安装
