### ISSUE TITLE
访问requirejs.org时循环重定向 301

### ISSUE THREAD

**Issue by jingzhou123** [jiacai2050/gooreplacer.xpi#12]

**Comment by jiacai2050** [comment]
```
curl https://ajax.lug.ustc.edu.cn/ajax/libs/dojo/1.4/dojox/highlight/resources/highlight.css
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.5.3</center>
</body>
</html>
```

估计是中科大服务器没配置好

**Comment by bojieli** [comment]
这是由于之前我们为了加快访问速度，使用 HTTP 访问 Google Fonts。现在 Google 方面强制把 HTTP 跳转到 HTTPS，从而导致请求被 301 到 https://ajax.googleapis.com 。现在已经改成使用 HTTPS 访问 Google Fonts，问题解决。

**Comment by jiacai2050** [comment]
谢谢你们的工作。
还有个404问题，https://store.playstation.com/ 这个网址，你用chrome审查元素看一下。
![snip20150504_54](https://cloud.githubusercontent.com/assets/3848910/7456375/9fdc93ba-f2b6-11e4-93f9-3e87f939c920.png)

**Comment by bojieli** [comment]
你好！

首先，我访问这个 https://store.playstation.com/ 没有发现载入 ajax.lug.ustc.edu.cn
域下的资源，也没有发现 404 错误。我这里该网站被重定向到
https://store.playstation.com/#!/en-sg/home/games ，有可能是中国区的配置不同。

其次，我访问了你图片中的两个 URL：
1. https://ajax.lug.ustc.edu.cn/ajax/libs/jquery/1.10.3/jquery-ui.min.js
确实是 404，而 Google 源站也是 404. (
https://ajax.googleapis.com/ajax/libs/jquery/1.10.3/jquery-ui.min.js)
2. https://ajax.lug.ustc.edu.cn/ajax/libs/jquery/1.10.2/jquery.min.js
可以正常返回 jquery 库。

**Comment by jiacai2050** [comment]
好的，了解了。

看来是sony的问题，正确的地址应该是：
https://ajax.lug.ustc.edu.cn/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js
现在已经没问题了。 :+1:
