### ISSUE TITLE
火狐下，dojo官方的一个说明文档中加载的ajax.googleapis.com链接，有些能替换，有些不能替换

### ISSUE THREAD

**Issue by ylyxf** [jiacai2050/gooreplacer.xpi#15]
作者，您好，访问一个dojo的官方帮助文档时，发现有的链接能被替换，有的链接不能被替换 ，有没有可能是dojo特殊的加载方式引起的？
http://dojotoolkit.org/documentation/tutorials/1.10/form_manager/demo/manager.html
![1](https://cloud.githubusercontent.com/assets/3871920/10263614/3e483de6-6a27-11e5-8c58-6491ab4bd728.jpg)
![Uploading 2.jpg…]()

**Comment by meteormatt** [comment]
我这里会跳转到 https://ajax.lug.ustc.edu.cn/ajax/libs/dojo/1.10.4/dojo/Stateful.js 的
