### ISSUE TITLE
与redirector扩展的区别是？

### ISSUE THREAD

**Issue by ivysrono** [jiacai2050/gooreplacer.xpi#19]
Redirector :: Firefox 附加组件
https://addons.mozilla.org/zh-CN/firefox/addon/redirector/
因为gooreplacer支持在线规则，可以跨fx和chrome使用，所以我准备将firefox redirector 扩展的规则都转换过来，故有如下疑问：
1、注释写在哪？
2、能否限定某些规则只对地址栏重定向，不处理页内元素？
3、能否利用fx和chrome自带的同步功能，同步在线规则地址？

**Comment by jiacai2050** [comment]
1. 不支持为重定向规则添加注释
2. 这个目前不支持。好奇什么场景下会需要这种需求
3. 这个感觉没什么必要，chrome 直接用 localStorage 存储；firefox 使用 [simple-prefs](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs) API，支持同步功能

**Comment by ivysrono** [comment]
看来还是要分用两个扩展啊。
给个第二条的例子：
豆瓣跳过注册页面直接加密登陆
Redirect:
^https?:\/\/www.douban.com\/accounts\/register$
to:
https://www.douban.com/accounts/login
Example:
http://www.douban.com/accounts/register → https://www.douban.com/accounts/login
Applies to:
Main window (address bar)

**Comment by jiacai2050** [comment]
你这个例子没说明什么问题呀，只有在真正请求资源时才会去重定向

**Comment by ivysrono** [comment]
举个更准确的例子：
https://lh3.googleusercontent.com/-y0GT6EnR4Ow/VnoEYWVgSTI/AAAAAAAAwXs/ukGo03jBEiA/w530-h398-p/
-》
https://lh3.googleusercontent.com/-y0GT6EnR4Ow/VnoEYWVgSTI/AAAAAAAAwXs/ukGo03jBEiA/w0/

下面是原图，但如果页面中的缩略图一律替换为原图，那么一定会打乱整个页面布局，所以应当只在地址栏替换，也就是查看图片时才载入原图。
fx和chrome版的redirector都有这个选项。

**Comment by jiacai2050** [comment]
你这个例子倒是比较合理。

不过最近没有精力去研究这一块了，我不能保证在近期版本加上。周末有时间我会调研调研

**Comment by halee99** [comment]
gooreplacer4android安装成功，退出firefox后  gooreplacer4android插件被清除。求解决
