### ISSUE TITLE
能否顺带解决platform.twitter.com加载慢的问题？

### ISSUE THREAD

**Issue by skyline75489** [jiacai2050/gooreplacer.xpi#2]
不知道platform.twitter.com的oct.js，widget.js之类的有没有国内的Host?

**Comment by jiacai2050** [comment]
我搜了下， 貌似没有你说的js托管
不过你可以统计一下你遇到被墙的js，我可以利用github pages提供托管

**Comment by skyline75489** [comment]
除了googleapi系列的，目前就发现了platform.twitter.com的widget.js和oct.js有问题。 打开 https://education.github.com/pack 这个页面时会很慢

**Comment by jiacai2050** [comment]
我知道的还有google plus的分享按钮的js
http://apis.google.com/js/plusone.js
如果想要扩展性灵活些，最好是能够提供接口，让用户自定义转化规则
chrome下已经有Switcheroo，firefox下已经有Redirector
我不知道还有没有必要接着做下去

**Comment by jiacai2050** [comment]
已经决定开发自定义功能，类似chrome上的Switcheroo，打算只支持*通配符
