### ISSUE TITLE
重定向后原请求不会关闭,依然继续请求.

### ISSUE THREAD

**Issue by Hacksign** [jiacai2050/gooreplacer.xpi#21]
firefox 44.0.2
比如请求fonts.googleapis.com
重定向的请求已经返回结果了,但是fonts.googleapis.com的请求依然在进行中,导致一直提示网页在加载.

**Comment by jiacai2050** [comment]
你应该是在 firebug 里面看到的吧，那是 firebug 的问题，你用 firefox 自带的 `Inspect Element` 来看是没问题的

**Comment by Hacksign** [comment]
的确是从firebug里面看到的.
汗...close的太快了...找了半天~~
