### ISSUE TITLE
跳转规则丰富一点

### ISSUE THREAD

**Issue by ed29** [jiacai2050/gooreplacer.xpi#22]
很好的插件，提供了自定义；有个个人看法是，作者可不可以分享一下自己日常使用的规则，甚至可以作为插件的默认规则，这样插件装好了，就可以开箱即用，皆大欢喜，是吧。毕竟要每个用户单独重复去维护个人的跳转规则库，倒不如一个集中的现成的规则库。

**Comment by fengyunhe** [comment]
有在线更新规则啊，更新下规则就自动替换了
