### ISSUE TITLE
新功能需求:直接drop掉某些request

### ISSUE THREAD

**Issue by Hacksign** [jiacai2050/gooreplacer.xpi#23]
场景:
youku.com目前会集成一些第三方广告公司的一些脚本,追踪用户.
例如:scorecardresearch.com
这些站会导致浏览器一直提示在加载.

需求:
当满足一些规则时,直接drop掉一些request请求.

这样只要规则得当,反而可以加快'加载'速度.

**Comment by jiacai2050** [comment]
确实有这种场景，这更像是现在的Adblock之类的插件，我近期打算重新审视下 gooreplacer 的功能定位，争取做到 Chrome 与 Firefox 上最好的的重定向扩展。

Stay Tuned
