### ISSUE TITLE
fonts.lug.ustc.edu.cn现在会显示循环重定向

### ISSUE THREAD

**Issue by meteormatt** [jiacai2050/gooreplacer.xpi#24]
https://fonts.lug.ustc.edu.cn/

> 此页面不能正确地重定向
> 
> Firefox 检测到该服务器正在将此地址的请求循环重定向。
> 
> ```
> 此问题可能是因为禁用或拒绝 Cookie 导致。
> ```

![qq20160513-2 2x](https://cloud.githubusercontent.com/assets/424475/15242203/6836a8cc-1927-11e6-936e-86e09f66c852.png)

原来
https://fonts.googleapis.com/css?family=Open+Sans 
会定向到 
https://fonts.lug.ustc.edu.cn/css?family=Open+Sans 
现在一直转圈不能打开

禁用`gooreplacer`后可以打开

**Comment by jiacai2050** [comment]
好的， 这个周末我看下，谢谢反馈。

**Comment by meteormatt** [comment]
现在好了
