### ISSUE TITLE
360挂了

### ISSUE THREAD

**Issue by ivysrono** [jiacai2050/gooreplacer.xpi#26]
可以把360的集成进来了吧。

另外，中科大的源地址是不是变了？

https://fonts.googleapis.com/css?family=Open+Sans
--》
https://fonts.proxy.ustclug.org/css?family=Open+Sans

**Comment by jiacai2050** [comment]
https://fonts.lug.ustc.edu.cn/css?family=Open+Sans

会 301 到

https://fonts.proxy.ustclug.org/css?family=Open+Sans

如果想改这些规则，自己可以托管个。
