### ISSUE TITLE
v0.6 自定义规则界面无效

### ISSUE THREAD

**Issue by lexil** [jiacai2050/gooreplacer.xpi#6]
如图所示，点击自定义规则：
![01](https://cloud.githubusercontent.com/assets/9199948/5084319/b1d169b0-6f3f-11e4-9661-f2dffc35e116.png)

**Comment by jiacai2050** [comment]
你的操作系统？firefox版本？是否用过v0.6之前的版本？

**Comment by lexil** [comment]
Windows 8.1 update 1 x64
Firefox 33.1/Firefox 33.1.1
之前的v0.4一直正常，

**Comment by jiacai2050** [comment]
出现这种情况,有可能是gooreplacer缓存的问题,你找到firefox扩展的本地路径,把gooreplacer相关的文件删除,重新安装应该就好了.
在linux上,路径为
/home/<username>/.mozilla/firefox/6dmcjuri.default/jetpack/gooreplacer@liujiacai.net
其中6dmcjuri是sessionid,每个人的都不一样,
xp的路径为:
C:\Documents and Settings<username>\Application Data\Mozilla\Firefox\Profiles<profile ID>.default\jetpack\gooreplacer@liujiacai.net

Win8我没用过,你自己找找看,有问题再联系我 :+1:

**Comment by lexil** [comment]
貌似找到问题所在，Firefox隐私模式下，就会出现此问题。正常模式下，扩展正常。
