### ISSUE TITLE
Mac下重定向失效

### ISSUE THREAD

**Issue by ghost** [jiacai2050/gooreplacer.xpi#9]
Mac下，点红色按钮关闭firefox窗口后再打开就会失效，但如果是退出firefox后再打开就没有这个问题。（Mac10.10，firefox35.01）

**Comment by jiacai2050** [comment]
这个应该是操作系统的原因，
http://unix.stackexchange.com/questions/4618/why-mac-applications-never-get-closed

如果要查出原因，需要了解firefox是如何响应close button的事件，目前我的没有看这段代码的时间。
如果你对C++比较熟悉，可以试试

**Comment by meteormatt** [comment]
点退出后就好了. Mac下的关闭, Firefox不会退出进程.
<img width="402" alt="qq20150930-1 2x" src="https://cloud.githubusercontent.com/assets/424475/10183310/ce92b5d0-6760-11e5-9103-47bed1102e4b.png">

**Comment by fengyc** [comment]
@jiacai2050 你好。这个问题很久了，你现在有解决方法了吗。好像firefox的 WebExtension 方式的扩展没有这个问题，我用你的在线规则和 WebExtension 在 MAC 下做了一个小程序自己在用，一直比较稳定。如果你有计划迁移到 WebExtension 上吗，我可以帮忙。

**Comment by jiacai2050** [comment]
@fengyc 
看了下 WebExtension 对 Firefox 的[版本要求](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Prerequisites)，必须要v45以上，问题应该不大，你要是感兴趣可以提交个 PR 来进行迁移，感谢了。

**Comment by fengyc** [comment]
@jiacai2050 WebExtension 方式和目前的 gooreplacer 代码差异太大了，不好整理。我另外开一个， https://github.com/fengyc/URLRedirector 。v45 好像还不行，可能是我有些 api 用得有问题，在windows 测试时 v45 上装不上去，升级到 49 之后才装上去了，目前在 mac 下运行稳定，上 stackoverflow 之类的网站快多了。

**Comment by jiacai2050** [comment]
不错。其实 gooreplacer 有对应的 Chrome 版本，你在 Chrome 版本上改就行，我现在已经改好了。

@fengyc 你可以参考 https://github.com/jiacai2050/gooreplacer4chrome
